//
// Created by donat on 26/08/2024.
//

#ifndef CONST_H
#define CONST_H

#define MAIN_SERVER_PORT 50202

#define MAIN_SERVER 1
#define CLIENT 2
#define GAME_ROOM 3
#define ANY 0

//Exemple for code:
//          1    |    0    |    0      4
//
//   From client | To serv | Operation ID
#define CLIENT_REQUEST_ALL_ROOMS 2101
#define CLIENT_REQUEST_ROOM_CREATION 2102
#define CLIENT_REQUEST_JOIN_ROOM 2103
#define CLIENT_REQUEST_QUIT_MS 2104


#define CLIENT_REQUEST_CONNECT_GR 2301
#define CLIENT_REQUEST_GET_STATUS 2302

#define GAME_ROOM_REQUEST_ROOM_STARTED 3201
#define GAME_ROOM_REQUEST_UPDATE_STATUS_MS 3102
#define GAME_ROOM_REQUEST_UPDATE_STATUS_CLIENT 3202
#define GAME_ROOM_REQUEST_END_CONNECTION 3203

#define GAME_ROOM_REQUEST_GAME_STARTING 3204


#define ACK 0001
#define EXT 0002

#define TRANSFERT_DELIMITER '|'

#define MAX_CLIENTS_PER_ROOM 2

#define BALL_ID 1
#define PADDLE_ID 2

#endif //CONST_H

